Models/ITodoRepository.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace RazorTodo.Models
{
    public interface ITodoRepository
    {
        Task<IEnumerable<Todo>> GetAll();
        Task Add(Todo todo);
        Task Remove(Guid id);
        Task<Todo> Find(Guid id);
        Task Update(Todo todo);
    }

}

Models/Todo.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace RazorTodo.Models
{
    public class Todo
    {
        public Todo()
        {
            Id = Guid.NewGuid();
        }

        public Guid Id { get; set; }

        [Required]
        public string Description { get; set; }

    }
}

Pages/Edit.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorTodo.Models;

namespace RazorTodo.Pages
{
    public class EditModel : PageModel
    {
        private readonly ITodoRepository _todoRepository;

        public EditModel(ITodoRepository todoRepository)
        {
            _todoRepository = todoRepository;
        }

        public Todo EditTodo { get; private set; }

        public async Task OnGetAsync(Guid id)
        {
            await GetEditTodo(id);
        }

        public async Task<IActionResult> OnPostAsync(Todo todo)
        {
            if (ModelState.IsValid)
            {
                await _todoRepository.Update(todo);
                return RedirectToPage("Index");
            }
            return RedirectToPage();
        }

        private async Task GetEditTodo(Guid id)
        {
            EditTodo = await _todoRepository.Find(id);
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using RazorTodo.Models;

namespace RazorTodo.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ITodoRepository _todoRepository;
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ITodoRepository todoRepository, ILogger<IndexModel> logger)
        {
            _todoRepository = todoRepository;
            _logger = logger;
        }

        [TempData]
        public string Message { get; set; }

        [BindProperty]
        public IEnumerable<Todo> Todos { get; private set; }

        public async Task OnGetAsync()
        {
            await GetTodos();
        }

        public async Task<IActionResult> OnPostAsync(Todo todo)
        {
            await OnGetAsync();
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _todoRepository.Add(todo);
            Message = $"Added: {todo.Description}";
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemoveAsync(Guid id)
        {
            if (ModelState.IsValid)
            {
                await _todoRepository.Remove(id);
                return RedirectToPage();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostEditAsync(Guid id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if ((await _todoRepository.Find(id) != null))
            {
                return RedirectToPage("Edit", new { id = id });
            }

            return Page();
        }

        private async Task GetTodos()
        {
            Todos = await _todoRepository.GetAll();
        }
    }
}

Pages/Edit.cshtml
@page
@model EditModel
@{
    <h1>Todo List</h1>
    <h4>Edit a todo: @Model.EditTodo.Description</h4>
    <form asp-page="Edit" method="post" class="form-inline">
        <input type="hidden" name="Id" value="@Model.EditTodo.Id">
        <input type="text" name="Description" placeholder="Description" id="Description" class="form-control">
        <button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o" aria-hidden="true"></i></button>
    </form>
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1>Todo List</h1>
<h4>Add a todo</h4>
<p class="text-success">@Model.Message</p>
<form asp-page="Index" method="POST" class="form-inline">
    <input type="text" name="Description" id="Description" class="form-control" placeholder="Description">
    <button type="submit" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> Add </button>
</form>
<div asp-validation-summary="All"></div>
<h4>Current Todo's</h4>

@if (!Model.Todos.Any())
{
    <p class="empty">The list is empty</p>
}
else
{
    <ul class="list-unstyled">
        @foreach (var todo in Model.Todos)
        {
            <li>
                <form method="post" asp-page="Index" asp-page-handler="Remove" style="display: inline">
                    <input type="hidden" name="Id" value="@todo.Id">
                    <button type="submit" class="btn btn-link"><i class="fa fa-trash" aria-hidden="true"></i></button>
                </form>
                <form method="post" asp-page="Index" asp-page-handler="Edit" style="display: inline">
                    <input type="hidden" name="Id" value="@todo.Id">
                    <button type="submit" class="btn btn-link"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                </form>
                @todo.Description
            </li>
        }
    </ul>
}

<style>
    .validation-summary-errors ul {
        list-style-type: none;
        color: red;
        padding:0;
        margin:0;
    }
    .empty {
        color: lightgray;
    }
</style>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorTodo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RazorTodo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - RazorTodo - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>